# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "lioooo_utils"
  s.version = "0.3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["liooo"]
  s.date = "2014-04-20"
  s.description = "this gem for lioooo common utils like log or file controll etc."
  s.email = "lb563@foxmail.com"
  s.executables = ["liooo_link_log_dir"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "lib/lioooo_log.rb",
    "lib/lioooo_utils.rb",
    "lib/sigcheck.rb",
    "lib/utils.rb",
    "lib/version.rb"
  ]
  s.homepage = "http://github.com/mrli/lioooo_utils"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "use it for common log"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<colored>, ["= 1.2"])
      s.add_runtime_dependency(%q<logging>, ["= 1.8.1"])
      s.add_runtime_dependency(%q<activesupport>, ["= 3.2.16"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<colored>, ["= 1.2"])
      s.add_dependency(%q<logging>, ["= 1.8.1"])
      s.add_dependency(%q<activesupport>, ["= 3.2.16"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<colored>, ["= 1.2"])
    s.add_dependency(%q<logging>, ["= 1.8.1"])
    s.add_dependency(%q<activesupport>, ["= 3.2.16"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

